dist: trusty
language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"

install:
  - pip install pytest pytest-cov codecov
  - pip install -e . -q

script:
  - pytest --cov=./ --tb=short
